---
root: true

plugins:
  - jest
  - babel

env:
  node: true
  jest: true
  browser: true

parser: "@babel/eslint-parser"

parserOptions: 
  parser: '@babel/eslint-parser'
  requireConfigFile: false
  ecmaVersion: 2018
  sourceType: 'module'

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

rules:
  no-console: 0
  import/extensions: 0
